### PR TITLE
Rebuild civix for PHP 7.4 support

### PR DESCRIPTION
**Pull request by IProSoft**
Extension is outdated and throw error in PHP 7.4

PHP Deprecated: Array and string offset access syntax with curly braces is deprecated

FIX: rebuild civix with built in function civix generate:module

### CODE REVIEW

**Comment by IProSoft** [comment]
Is there chance to pull this changes ?

**Comment by mlutfy** [comment]
hi @jaapjansma I reviewed the PR and looks OK to me. Any chance you could merge it and tag a new release?

I am trying to help with PHP 8 adoption: https://civicrm.org/blog/bgm/php-8-support-civicrm-extensions

I can also help with moving the extension to Gitlab if you'd like, and with minor fixes like this (but to move the extension I'd need to be an admin on the project, or you can import to Gitlab and I can continue from there).

**Comment by jaapjansma** [comment]
@mlutfy I have merged this PR and created a new release.

**Comment by mlutfy** [comment]
@jaapjansma Thanks! I updated the blog post.

**Pull request merged**
